fw_cfg: Use fw_cfg to convey platform information
intel/nemu pull request #112
Opened 2018-10-02 18:40 UTC by mcastelino

Firmware (and OS) today uses the device id of the host bridge
as a means of determining the platform on which it is running.
Use fw_cfg instead to send this information. This will allow it
to be decoupled from PCI (as it should be) in the case of a
virtual platform.

Signed-off-by: Manohar Castelino <manohar.r.castelino@intel.com>

The initialization is performed outside of `fw_cfg_init` as `fw_cfg_init` 
seems to be a little more generic. Or we can add this as a parameter
to fw_cfg_init.

2018-10-02 18:43 UTC, mcastelino commented
Related https://github.com/rbradford/edk2/pull/3

2018-10-02 19:21 UTC, sameo commented on include/hw/i386/virt.h
> +#define VIRT_QEMU_GPEX_DEVICE_ID 0x8
I guess `0x8` is coming from the PCI DID that the GPEX host currently uses?

2018-10-02 19:35 UTC, sboeuf commented on include/hw/i386/virt.h
> +#define VIRT_QEMU_GPEX_DEVICE_ID 0x8
Yeah I think so since this code only changes the way to pass this value, not the value itself.

2018-10-02 19:35 UTC, sboeuf approved these changes

2018-10-03 11:45 UTC, rbradford requested changes
I'm blocking this merge only because of needing to iterate on / discuss the value. The change itself is great and I think it is so much better than relying on PCI probing.

2018-10-03 11:45 UTC, rbradford commented on include/hw/i386/virt.h
> +#define VIRT_QEMU_GPEX_DEVICE_ID 0x8
As we're going to be moving away from using the GPEX DID for the PCI lite host bridge we should use this as an opportunity to use a better value for the machine type. It's important that we get this right as once we start upstreaming the OVMF changes we're not going to be able to modify it.

2018-10-03 16:16 UTC, mcastelino commented
> As we're going to be moving away from using the GPEX DID for the PCI lite host bridge we should use this as an opportunity to use a better value for the machine type. It's important that we get this right as once we start upstreaming the OVMF changes we're not going to be able to modify it.

@rbradford we should completely decouple the machine id from PCI DID. So we can use a machine id here and then OVMF can choose to map it to something else like the PCI DID. However machine id is not used consistently in QEMU.

The few examples I found are
```
enum cxmachines {
    CALXEDA_HIGHBANK,
    CALXEDA_MIDWAY,
};
```
```
enum {
    ss5_id = 32,
    vger_id,
    lx_id,
    ss4_id,
    scls_id,
    sbook_id,
    ss10_id = 64,
    ss20_id,
    ss600mp_id,
};
```

```
enum {
    ARCH_PREP = 0,
    ARCH_MAC99,
    ARCH_HEATHROW,
    ARCH_MAC99_U3,
};
```

Maybe we define an enum for x86 machine types?

2018-10-03 16:18 UTC, rbradford commented
@mcastelino Decoupling and using an enums gets a big :+1: from me

2018-10-03 22:06 UTC, mcastelino commented
@rbradford addressed your comments. Also https://github.com/rbradford/edk2/pull/3 has been updated to incorporate this change.

2018-10-04 10:21 UTC, sameo commented on include/hw/i386/pc.h
> +
That looks good to me, but could we move that enum either under a new `include/hw/i386/machine.h` file or under the already existing `include/hw/i386/fw.h` one?

2018-10-04 16:44 UTC, merged