Remove isa-bios memory region in virt platform
intel/nemu pull request #158
Opened 2018-10-25 06:48 UTC by yangzhon

When i use "info qom-tree" command and find "/isa-bios[0] (qemu:memory-region)" in memory region list.

The isa-bios is not useful in virt platform and i added one bool parameter to check this.

By the way, this patch also fixed another pflash issue in x86.
Memory.c (hw\i386\virt):    sysfw_firmware_init(system_memory, true);

void sysfw_firmware_init(MemoryRegion *rom_memory, bool isapc_ram_fw)
{
    DriveInfo *pflash_drv;

    pflash_drv = drive_get(IF_PFLASH, 0, 0);

    if (isapc_ram_fw || pflash_drv == NULL) {
        /* When a pflash drive is not found, use rom-mode */
        old_pc_system_rom_init(rom_memory, isapc_ram_fw);
        return;
    }

    if (kvm_enabled() && !kvm_readonly_mem_enabled()) {
        /* Older KVM cannot execute from device memory. So, flash memory
         * cannot be used unless the readonly memory kvm capability is present. */
        fprintf(stderr, "qemu: pflash with kvm requires KVM readonly memory support\n");
        exit(1);
    }

    pc_system_flash_init(rom_memory);
}

If we use pflash to flash UEFI bios, the sysfw_firmware_init() still call old_pc_system_rom_init(), the right operation is to call pc_system_flash_init() for pflash. So the cuurent pc_system_flash_init() is not useful.

Please @sameo @rbradford help review this patch, thanks!

2018-10-25 07:42 UTC, yangzhon commented
Robs' commit (bc9ed74), 
diff --git a/hw/i386/virt/memory.c b/hw/i386/virt/memory.c
index ee0693a543..e0461c19e2 100644
--- a/hw/i386/virt/memory.c
+++ b/hw/i386/virt/memory.c
@@ -99,7 +99,7 @@ MemoryRegion *virt_memory_init(VirtMachineState *vms)
                                     &machine->device_memory->mr);
     }

-    sysfw_firmware_init(system_memory, false);
+    sysfw_firmware_init(system_memory, true);

This make bios memory region read/write, if the change like this, pc_system_flash_init(rom_memory) is not useful, do we need remove CONFIG_PFLASH_CFI01=y in virt target mk file ?

2018-10-25 09:08 UTC, rbradford requested changes
Not a reflection on your patch but I don't want to merge this until we have qboot / kernel direct boot testing integrated into NATS.

2018-11-21 10:28 UTC, sameo commented
@yangzhon We realized that at least seabios needs that region and we are going to support seabios as well. I think we should close that PR.

2018-11-21 10:33 UTC, yangzhon commented
@sameo ,

Yes, i will close this PR, thanks!

2018-11-21 10:33 UTC, closed without merging