sysfw: Remove FLASH build dependency and isa-bios region allocation
intel/nemu pull request #178
Opened 2018-11-16 15:44 UTC by sameo

Supersedes #158

2018-11-19 08:22 UTC, rbradford commented
@sameo  build error:

```
/home/agentadmin/workspace/nemu_PR-178-SSNOAENHEXKTKD6MOEMF7POMAYE2OXRCNOMXAXCRFWU5GUVQAJUA/hw/i386/sysfw-flash.c:37:19: fatal error: sysfw.h: No such file or directory
compilation terminated.
/home/agentadmin/workspace/nemu_PR-178-SSNOAENHEXKTKD6MOEMF7POMAYE2OXRCNOMXAXCRFWU5GUVQAJUA/rules.mak:69: recipe for target 'hw/i386/sysfw-flash.o' failed
make[1]: *** [hw/i386/sysfw-flash.o] Error 1
make[1]: *** Waiting for unfinished jobs....
/home/agentadmin/workspace/nemu_PR-178-SSNOAENHEXKTKD6MOEMF7POMAYE2OXRCNOMXAXCRFWU5GUVQAJUA/hw/i386/sysfw.c:38:19: fatal error: sysfw.h: No such file or directory
compilation terminated.
/home/agentadmin/workspace/nemu_PR-178-SSNOAENHEXKTKD6MOEMF7POMAYE2OXRCNOMXAXCRFWU5GUVQAJUA/rules.mak:69: recipe for target 'hw/i386/sysfw.o' failed
make[1]: *** [hw/i386/sysfw.o] Error 1
Makefile:481: recipe for target 'subdir-x86_64-softmmu' failed
make: *** [subdir-x86_64-softmmu] Error 2
```

2018-11-19 08:25 UTC, rbradford reviewed
Looks good as a whole and I like the way it's structured. Can you test this with qboot too?

2018-11-19 08:49 UTC, yangzhon commented
@sameo , 

I ever wanted to remove CONFIG_PFLASH_CFI01 device model and isa-bios memory region, you did it, thanks!

2018-11-19 14:00 UTC, sameo commented
> @sameo build error:
> 
> ```
> /home/agentadmin/workspace/nemu_PR-178-SSNOAENHEXKTKD6MOEMF7POMAYE2OXRCNOMXAXCRFWU5GUVQAJUA/hw/i386/sysfw-flash.c:37:19: fatal error: sysfw.h: No such file or directory
> compilation terminated.
> /home/agentadmin/workspace/nemu_PR-178-SSNOAENHEXKTKD6MOEMF7POMAYE2OXRCNOMXAXCRFWU5GUVQAJUA/rules.mak:69: recipe for target 'hw/i386/sysfw-flash.o' failed
> make[1]: *** [hw/i386/sysfw-flash.o] Error 1
> make[1]: *** Waiting for unfinished jobs....
> /home/agentadmin/workspace/nemu_PR-178-SSNOAENHEXKTKD6MOEMF7POMAYE2OXRCNOMXAXCRFWU5GUVQAJUA/hw/i386/sysfw.c:38:19: fatal error: sysfw.h: No such file or directory
> compilation terminated.
> /home/agentadmin/workspace/nemu_PR-178-SSNOAENHEXKTKD6MOEMF7POMAYE2OXRCNOMXAXCRFWU5GUVQAJUA/rules.mak:69: recipe for target 'hw/i386/sysfw.o' failed
> make[1]: *** [hw/i386/sysfw.o] Error 1
> Makefile:481: recipe for target 'subdir-x86_64-softmmu' failed
> make: *** [subdir-x86_64-softmmu] Error 2
> ```

@rbradford This should be fixed now.

2018-11-19 15:27 UTC, sameo commented
@rbradford This works with qboot as well.

2018-11-19 17:43 UTC, sboeuf reviewed
Looks good overall, a few comments.

2018-11-19 17:43 UTC, sboeuf commented on hw/i386/sysfw.c
> +        pc_system_init(rom_memory, rw_fw);
Shouldn't we keep `rom` in the name? It would keep the information that we're initializing based on ROM here.

2018-11-19 17:43 UTC, sboeuf commented on hw/i386/sysfw.c
> -    pflash_drv = drive_get(IF_PFLASH, 0, 0);
Definitely, especially if this variable is not reused later.

2018-11-19 17:43 UTC, sboeuf commented on hw/i386/Makefile.objs
> +obj-$(CONFIG_PFLASH_CFI01) += sysfw-flash.o
Comment about the commit `hw: i386: Separate the pflash emulation from sysfw `:
- There's a typo in the commit message: `inly` should be `only`.
- The change looks fine and is enough to compile the flash out, but I was thinking, it might be more appropriate to split into 3 different files `sysfw.c` (common functions), `sysfw-ram.c` (ram specific), and `sysfw-flash.c` (flash specific), WDYT?

2018-11-19 17:43 UTC, sboeuf commented on hw/i386/sysfw.c
> -                                        1);
An explanation about why this might have been needed in the past, and why now we can remove it, would be great in the commit message :)

2018-11-19 17:58 UTC, rbradford requested changes
This breaks seabios for Q35 (and virt.)

2018-11-20 14:28 UTC, sameo commented
The 128K mapping right below 1M is needed by seabios at least. I removed that patch, we'd need it and we'll need that region for supporting at least seabios.

2018-11-20 14:35 UTC, sameo commented on hw/i386/sysfw.c
> +        pc_system_init(rom_memory, rw_fw);
Well we're loading and mapping the firmware code into read-only or regular memory, so `rom` is a bit outdated. I updated the name to `pc_system_firmware_init()` instead.

2018-11-20 14:40 UTC, sameo commented on hw/i386/Makefile.objs
> +obj-$(CONFIG_PFLASH_CFI01) += sysfw-flash.o
> Comment about the commit `hw: i386: Separate the pflash emulation from sysfw `:
> 
> * There's a typo in the commit message: `inly` should be `only`.

Fixed, thanks.

> * The change looks fine and is enough to compile the flash out, but I was thinking, it might be more appropriate to split into 3 different files `sysfw.c` (common functions), `sysfw-ram.c` (ram specific), and `sysfw-flash.c` (flash specific), WDYT?

I think it's a little complex for such small change and e.g. sysfw.c would end up being around 20 lines long only.

2018-11-20 15:05 UTC, rbradford approved these changes

2018-11-20 16:17 UTC, sboeuf commented on hw/i386/Makefile.objs
> +obj-$(CONFIG_PFLASH_CFI01) += sysfw-flash.o
Oh so there's basically no common functions between ram and flash. Then, that's fair, let's leave it this way :)

2018-11-20 16:21 UTC, sboeuf approved these changes

2018-11-21 10:27 UTC, merged