add pci dsdt and mmcfg support
intel/nemu pull request #26
Opened 2018-07-23 14:15 UTC by yangzhon

Those patches added the pci dsdt support from q35/pc platform and guest kernel can normally show pci bus log.  Since virt/i386 default bus is pcie, i added the mmcfg support for guest kernel.

Some issues need to be talked
(1) build_prt(), build_crs(), build_gsi_link_dev(), build_osc_method() are moved to  hw/acpi/aml-build.c ? 
     The current patch is still in i386/acpi-build.c

Please @sameo @rbradford @liujing2 help review those 3 patches, thanks!

2018-07-23 15:46 UTC, sameo requested changes

2018-07-23 15:46 UTC, sameo commented on include/hw/acpi/aml-build.h
> +/*acpi-build.c*/
Nitpick: Either we add a comment that describes what those structures are, and not simply where they come from, or we don't comment at all. I prefer the former.

2018-07-23 15:46 UTC, sameo commented on include/hw/acpi/aml-build.h
> +void crs_range_set_free(CrsRangeSet *range_set);
Another nit: Can we group the `crs_*` routines definitions together?

2018-07-23 15:46 UTC, sameo commented on hw/i386/acpi-build.c
> +Aml *build_osc_method(void)
All those general routines are not x86 specific, so could you please create a separate patch that move them from `i386/acpi-build.c` to `aml-build.c` ?

2018-07-23 15:46 UTC, sameo commented on hw/i386/acpi-build.c
> +
That one is a `acpi_get_i386_pci_host` fix, and I'd love to see it as a standalone patch in this PR.
I also think that it should not be i386 specific and we could have a list of QEMU supported PCI host strings list and have this routine look like that:

```C
static char *pci_hosts[] = {
   "/machine/i440fx",
   "/machine/q35",
   "/machine/pcilite",
   NULL,
};

static Object *acpi_get_pci_host(void)
{
    PCIHostState *host;
    int i = 0;

    while (pci_hosts[i]) {
          host = OBJECT_CHECK(PCIHostState,
                        object_resolve_path(pci_hosts[i], NULL),
                        TYPE_PCI_HOST_BRIDGE);
          if (host) {
              return OBJECT(host);
          }

          i++;
    }

    return NULL;
}
```

2018-07-23 15:46 UTC, sameo commented on hw/acpi/reduced.c
> +}
I'd prefer for this one to not be under `acpi/reduced.c`. Is it generic enough to make it part of `aml-build.c` ?

2018-07-23 15:46 UTC, sameo commented on hw/acpi/reduced.c
> +    if (bus) {
We should assert that there is a bus. We won't support cases where `bus` is NULL.

2018-07-23 15:46 UTC, sameo commented on hw/acpi/reduced.c
> +
A few comments on this chunk:

* There are quite a few hardcoded numbers: `0x0CF8, 0x0CF8, 0x01, 0x080x000A0000, 0x000BFFFF, 0, 0x00020000`, etc. We need to have definitions for those.
* There are no comments, we need to put some explanations on what we're trying to do here.
* `build_dsdt` is now getting too big. We should split it by e.g. putting the above block of code into its own separate function, for PCI DSDT settings.

2018-07-23 15:46 UTC, sameo commented on hw/acpi/reduced.c
> +        build_mcfg(tables_blob, tables->linker, &mcfg);
Could we please add a `mcfg` method to `struct FirmwareBuildMethods`, set `i386/virt.c` `mcfg` pointer to point at `build_mcfg` and call `mc->firmware_build_methods.acpi.mcfg`.

2018-07-23 15:46 UTC, sameo commented on hw/i386/acpi-build.c
> +build_mcfg(GArray *table_data, BIOSLinker *linker, AcpiMcfgInfo *info)
Could we please move that one to `aml-build.c` as well?

2018-07-23 15:46 UTC, sameo commented on include/hw/acpi/acpi.h
> +/*acpi-build.c*/
Same comment as before: It would be better to have a more meaningful comment here.

2018-07-23 15:47 UTC, sameo commented
@yangzhon Thanks for the PR. I have a few comments, mostly about code reorganization and factorization.

2018-07-24 03:15 UTC, yangzhon commented on hw/i386/acpi-build.c
> +
okay, got it, thanks!

2018-07-24 05:19 UTC, yangzhon commented on hw/i386/acpi-build.c
> +build_mcfg(GArray *table_data, BIOSLinker *linker, AcpiMcfgInfo *info)
Yes, done,thanks!

2018-07-24 05:20 UTC, yangzhon commented on hw/i386/acpi-build.c
> +Aml *build_osc_method(void)
Yes, done, thanks!

2018-07-24 06:07 UTC, yangzhon commented on include/hw/acpi/aml-build.h
> +void crs_range_set_free(CrsRangeSet *range_set);
@sameo , the below crs_* related struct and functions are used in general, other are static functions in hw/i386/acpi-build.c. What's youe meaning about "group" ?   remove the line 445 as above shown or move all crs_* here? thanks!

btw, whether we need move all crs_* related functions into aml-build.c ?

+typedef struct CrsRangeEntry {                                                 
+    uint64_t base;                                                             
+    uint64_t limit;                                                            
+} CrsRangeEntry;                                                               
+                                                                               
+typedef struct CrsRangeSet {                                                   
+    GPtrArray *io_ranges;                                                      
+    GPtrArray *mem_ranges;                                                     
+    GPtrArray *mem_64bit_ranges;                                               
+} CrsRangeSet;                                                                 
+                                                                                                                         
+void crs_range_set_init(CrsRangeSet *range_set);                               
+Aml *build_crs(PCIHostState *host, CrsRangeSet *range_set);                    
+void crs_replace_with_free_ranges(GPtrArray *ranges,                           
+                                  uint64_t start, uint64_t end);               
+void crs_range_set_free(CrsRangeSet *range_set);                               
+void acpi_get_pci_holes(Range *hole, Range *hole64);

2018-07-24 06:21 UTC, yangzhon commented on hw/acpi/reduced.c
> +}
Yes, remove it to aml-build.c, thanks!

2018-07-24 07:05 UTC, yangzhon commented on hw/acpi/reduced.c
> +    if (bus) {
Yes, you are right, the assert(bus) will be added, thanks!

2018-07-24 07:58 UTC, sameo commented on include/hw/acpi/aml-build.h
> +void crs_range_set_free(CrsRangeSet *range_set);
@yangzhon I just meant to put the `crs_*` functions next to each others in the header file, but I see that they're already are grouped together. Forget about my comment, sorry for the confusion.

I think it would make sense to move all the `crs_*` routines into aml-build.c if they're not i386 specific.

2018-07-24 11:14 UTC, yangzhon commented on include/hw/acpi/aml-build.h
> +/*acpi-build.c*/
yes, i will add comments here, thanks!

2018-07-24 13:14 UTC, yangzhon commented on hw/acpi/reduced.c
> +        build_mcfg(tables_blob, tables->linker, &mcfg);
thanks, new version did it.

2018-07-24 13:16 UTC, yangzhon commented on include/hw/acpi/acpi.h
> +/*acpi-build.c*/
The new version patches did not add definition here, all definitions are in aml-build.h, so omit this. thanks!

2018-07-24 13:18 UTC, yangzhon commented on hw/acpi/reduced.c
> +
Yes, i moved the pci related acpi function into aml-build.c and build_dsdt() only call  acpi_dsdt_add_pci() for pci acpi setting like arm did.

2018-07-25 07:53 UTC, yangzhon commented on hw/acpi/reduced.c
> +
@sameo ,

I add the macro define for 0xcf8, 0xa0000 and etc, which make code more clear.
The comments are also added into the related code to explain which mem or io region is set in the aml table.  thanks!

2018-07-25 07:58 UTC, yangzhon commented
The new patches are ready, and i changed those according to samuel's comments. thanks sameo!
 
Please @sameo @rbradford @liujing2 help review those 5 patches, thanks!

2018-07-25 09:30 UTC, sameo requested changes

2018-07-25 09:30 UTC, sameo commented on hw/acpi/aml-build.c
> +    aml_append(sb_scope, build_gsi_link_dev("LNKD", 0x13, 0x13));
This PCI irq routing is quite standard and not really PCI lite specific, isn't it?
I would rename this one to something like `build_pci0_standard_int`.

2018-07-25 09:30 UTC, sameo commented on hw/acpi/aml-build.c
> +    bus = VIRT_MACHINE(machine)->pci_bus;
Please pass the `PCIBus` pointer as a function argument. We should not be linked to the `i386/virt` code in aml-build.c.

2018-07-25 09:30 UTC, sameo commented on hw/acpi/aml-build.c
> +static void build_lite_pci_host_bridge(Aml *table, Range *pci_hole,
Same here: How is this PCI lite specific? Isn't that routine building a standard, minimal PCI host bridge AML?

2018-07-25 09:30 UTC, sameo commented on hw/acpi/aml-build.c
> +#define VGA_MEM_LEN                        0x20000
Nice, thanks.

2018-07-25 09:30 UTC, sameo commented on hw/acpi/aml-build.c
> +    build_lite_pci_host_bridge(table, pci_hole, pci_hole64, machine);
So this function should also take a `PCIBus` pointer as an argument, and if it is not `NULL` then we call the 2 above functions. This will make this part of the code not dependent on `i386/virt` and reusable if we ever decide to not have a PCI bus at all.

2018-07-25 09:30 UTC, sameo commented on hw/acpi/reduced.c
> +                       MachineState *machine)
Ditto here. Maybe we should even have a ACPI specific PCI structure:

```C
struct AcpiPciBus {
   PCIBus *pci_bus;
   Range *pci_hole;
   Range *pci_hole64;
};
```

Up to you.

2018-07-25 09:30 UTC, sameo commented on include/hw/acpi/aml-build.h
> +void crs_range_set_free(CrsRangeSet *range_set);
So if we declare those functions in `aml-build.h` but define them in `i386/acpi-build.c` a non i386 machine type won't be able to include aml-build.h.
So I think we should define them in `aml-build.c`. @yangzhon Why is it difficult?

2018-07-26 02:00 UTC, yangzhon commented on hw/acpi/reduced.c
> +                       MachineState *machine)
Yes, i did it, thanks!

2018-07-26 02:02 UTC, yangzhon commented on hw/acpi/aml-build.c
> +    bus = VIRT_MACHINE(machine)->pci_bus;
Yes, i changed this, thanks!

2018-07-26 05:40 UTC, yangzhon commented on include/hw/acpi/aml-build.h
> +void crs_range_set_free(CrsRangeSet *range_set);
I have moved those routines into aml-build.c, thanks!

2018-07-26 11:29 UTC, yangzhon commented on hw/acpi/aml-build.c
> +    bus = VIRT_MACHINE(machine)->pci_bus;
New code has changed it, thanks!

2018-07-26 11:30 UTC, yangzhon commented on hw/acpi/aml-build.c
> +static void build_lite_pci_host_bridge(Aml *table, Range *pci_hole,
Yes, this build_lite_pci_host_bridge can be shared between virt-i386, pc and q35.

2018-07-26 11:31 UTC, yangzhon commented on hw/acpi/aml-build.c
> +    build_lite_pci_host_bridge(table, pci_hole, pci_hole64, machine);
Yes, did it, thanks!

2018-07-26 12:25 UTC, yangzhon commented on hw/acpi/aml-build.c
> +    aml_append(sb_scope, build_gsi_link_dev("LNKD", 0x13, 0x13));
@sameo, i am ready to delete this function because we will only support MSI.

2018-07-26 12:52 UTC, yangzhon commented
@sameo @rbradford,

Please help review this new patches, thanks!

2018-07-26 16:31 UTC, sameo requested changes
Almost there. I only have 2 comments to address and then we can merge that PR.

2018-07-26 16:31 UTC, sameo commented on hw/pci-host/pci_lite.c
> +PCIBus *pci_lite_init(VirtMachineState *vms,
In order to keep this code not `virt` specific, we should pass a `bool nofw` argument to this function instead of bringing a `virt.h` dependency.

2018-07-26 16:31 UTC, sameo commented on hw/pci-host/pci_lite.c
This `pci_lite.c` change is not related to this patch and looks like a fix. It should be moved into its own patch.

2018-07-26 16:39 UTC, rbradford commented on hw/pci-host/pci_lite.c
> +    DEFINE_PROP_BOOL("x-pci-hole64-fix", PCILiteHost, pci_hole64_fix, true),
Why do we need this? You default it to true, and nobody ever sets it to false so please remove the option or remove this.

2018-07-27 02:28 UTC, yangzhon commented on hw/pci-host/pci_lite.c
> +PCIBus *pci_lite_init(VirtMachineState *vms,
okay, thanks, which make code more clean.

2018-07-27 05:53 UTC, yangzhon commented on hw/pci-host/pci_lite.c
@sameo ,@rbradford

I investigated it again, this e820_add_entry() should be called only in nofw solution and seabios will handle it. We have better verify this with new OVMF bios, let me keep this fix until we do the integrate with new OVMF bios. 

In this time, i will remove this changes.  thanks again!

2018-07-27 06:29 UTC, yangzhon commented
@sameo @rbradford,

Please help review this new patches, and the changes as below:
(1). Removed the "x-pci-hole64-fix" option.
(2). Removed e820_add_entry() related changes for PCIe BAR, and keep this fix until when we do the integrate test with new OVMF bios.

thanks!

2018-07-27 08:17 UTC, sameo approved these changes

2018-07-27 08:17 UTC, sameo commented
LGTM

2018-07-27 09:19 UTC, sameo commented
I get the following ACPI tables when running a clear cloud image on top of this PR:

```
[    0.000000] ACPI: RSDP 0x000000001FBFA014 000024 (v02 OVMF  )
[    0.000000] ACPI: XSDT 0x000000001FBF90E8 00003C (v01 OVMF   OVMFEDK2 20130221      01000013)
[    0.000000] ACPI: FACP 0x000000001FBF8000 0000F4 (v03 OVMF   OVMFEDK2 20130221 OVMF 00000099)
[    0.000000] ACPI: DSDT 0x000000001FBF6000 000D57 (v01 INTEL  OVMF     00000004 INTL 20160108)
[    0.000000] ACPI: FACS 0x000000001FBFE000 000040
[    0.000000] ACPI: APIC 0x000000001FBF7000 000090 (v01 OVMF   OVMFEDK2 20130221 OVMF 00000099)
[    0.000000] ACPI: SSDT 0x000000001FBF5000 000057 (v01 REDHAT OVMF     00000001 INTL 20160108)
[    0.000000] ACPI: Local APIC address 0xfee00000
```

We need to fix that before merging.

2018-07-27 10:59 UTC, rbradford requested changes
It should look something like:

```
[    0.000000] ACPI: RSDP 0x000000001FBFA014 000024 (v02 BOCHS )
[    0.000000] ACPI: XSDT 0x000000001FBF90E8 000034 (v01 BOCHS  BXPCFACP 00000001      01000013)
[    0.000000] ACPI: FACP 0x000000001FBF7000 00010C (v05 BOCHS  BXPCFACP 00000001 BXPC 00000001)
[    0.000000] ACPI: DSDT 0x000000001FBF8000 00008B (v02 BOCHS  BXPCDSDT 00000001 BXPC 00000001)
[    0.000000] ACPI: APIC 0x000000001FBF6000 000080 (v01 BOCHS  BXPCAPIC 00000001 BXPC 00000001)
```

2018-07-27 11:04 UTC, rbradford commented
Here is the OVMF error message: 
```
ProcessCmdAddPointer: invalid pointer location or size in "etc/acpi/tables"
```

2018-07-27 13:24 UTC, yangzhon commented
@sameo @rbradford,

This NEW PR fixed the below issue:
ProcessCmdAddPointer: invalid pointer location or size in "etc/acpi/tables"

If we want to debug MMCFG config in guest, please mask below code in hw/pci-host/pci_lite.c
e820_add_entry(PCI_LITE_PCIEXBAR_BASE, PCI_LITE_PCIEXBAR_SIZE,
                   E820_RESERVED);

2018-07-27 15:41 UTC, rbradford approved these changes

2018-07-27 15:42 UTC, rbradford commented
I've pushed two commits, which with OVMF revision a76b242ca9 will result in a correct memory map in the guest.

2018-07-30 11:26 UTC, rbradford commented
@sameo you can test this with https://github.com/rbradford/edk2/releases/download/0.1/OVMF.fd

2018-07-30 11:57 UTC, sameo commented
@rbradford works here with your OVMF binary, thanks.
Merging now.

2018-07-30 11:58 UTC, merged