Shutdown and Reboot support
intel/nemu pull request #33
Opened 2018-08-01 09:56 UTC by liujing2

@sameo @rbradford @yangzhon 
I submitted the shutdown/reboot patches to review. Thanks!

2018-08-01 10:35 UTC, rbradford requested changes
Looking good. Some small changes please.

2018-08-01 10:35 UTC, rbradford commented on hw/acpi/aml-build.c
> +    build_append_gas_from_struct(tbl, &f->sleep_status_reg);
We don't need this as we are only implementing S5 and the OSPM is never going to read from it. Also you don't initialise this struct so it serves no purpose.

2018-08-01 10:35 UTC, rbradford commented on hw/i386/virt/acpi.c
> +    return d->sleep_control_regs;
The ACPI specification never talks about reading from this register. Have you seen code that expects to read from this register? If not please don't implement read on the ioport (which means you can remove the sleep_control_regs variable.)

2018-08-01 10:35 UTC, rbradford commented on include/hw/acpi/reduced.h
> +#define ACPI_REDUCED_SLEEP_ENABLE 0x0020 /* SLP_EN */
ACPI_REDUCED_SLEEP_ENABLE is only used in acpi.c so can be in that .c file i would also prefer (1 << 5) to 0x20

2018-08-01 10:35 UTC, rbradford commented on include/hw/acpi/reduced.h
> +#define ACPI_REDUCED_SLP_CNT_IOPORT 0x3B0
How did you choose this ioport? Also as the field is called SLEEP_CONTROL can you use the full name rather than shortening.

2018-08-01 10:35 UTC, rbradford commented on hw/i386/virt/acpi.c
> +                          &virt_sleep_cnt_ops, d, TYPE_VIRT_ACPI, 2);
You reserve two io-ports here. You should pass 1 as the last parameter.

2018-08-01 10:35 UTC, rbradford commented on hw/i386/virt/acpi.c
> +                          &virt_reset_cnt_ops, d, TYPE_VIRT_ACPI, 2);
Again, two i/o ports rather than one.

2018-08-01 10:35 UTC, rbradford commented on include/hw/acpi/reduced.h
> +#define ACPI_REDUCED_RST_CNT_IOPORT 0x3C0
The register is called RESET_REG in the spec (no CONTROL.)

2018-08-01 10:35 UTC, rbradford commented on hw/i386/virt/acpi.c
> +    .read = virt_acpi_reset_cnt_read,
Is read necessary here? I don't think so.

2018-08-01 10:35 UTC, rbradford commented on hw/i386/virt/acpi.c
> +    if (val & 4) {
This needs to match the value in RESET_VALUE from the FADT, i don't see you setting that so you must be reusing it. Can you add a #define to make it easier to understand (and use that in the FADT table.)

Also RESET_REG_SUP in the FADT needs to be enabled..is it?

2018-08-01 10:35 UTC, rbradford commented on hw/i386/virt/acpi.c
> +        case 5:
the \_S5 object in the DSDT needs to be set to the same value othewise this won't work for the Linux kernel.

2018-08-02 02:26 UTC, liujing2 commented on hw/acpi/aml-build.c
> +    build_append_gas_from_struct(tbl, &f->sleep_status_reg);
OK, got it. Will remove it.

2018-08-02 02:31 UTC, liujing2 commented on hw/i386/virt/acpi.c
> +    return d->sleep_control_regs;
When OVMF writes 2:4 bits (using function IoBitFieldWrite16()), it need firstly read from the ioport and then write. If only 1 bit is wrote, it doesn't need read firstly. So I can remove the RESET read callback.

2018-08-02 02:34 UTC, liujing2 commented on include/hw/acpi/reduced.h
> +#define ACPI_REDUCED_SLP_CNT_IOPORT 0x3B0
This port is originally used by "0x03B0-0x03DF : The range used for the IBM VGA".  I think virt platform won't use this device. 
OK, I will change the name to be full.

2018-08-02 02:38 UTC, liujing2 commented on hw/i386/virt/acpi.c
> +                          &virt_sleep_cnt_ops, d, TYPE_VIRT_ACPI, 2);
Will change to 1.

2018-08-02 02:39 UTC, liujing2 commented on hw/i386/virt/acpi.c
> +                          &virt_reset_cnt_ops, d, TYPE_VIRT_ACPI, 2);
Yes, the same. Will change.

2018-08-02 02:40 UTC, liujing2 commented on include/hw/acpi/reduced.h
> +#define ACPI_REDUCED_RST_CNT_IOPORT 0x3C0
Oh, got it.

2018-08-02 02:53 UTC, liujing2 commented on hw/i386/virt/acpi.c
> +    .read = virt_acpi_reset_cnt_read,
Hmm, according to the ovmf changes, I think this read callback is useless. I am not sure maybe we can discuss the ovmf changes firstly. Qemu depends on it.

2018-08-02 03:05 UTC, liujing2 commented on hw/i386/virt/acpi.c
> +    .read = virt_acpi_reset_cnt_read,
And I read the ich9_rst_cnt_read/ich9_rst_cnt_write in hw/isa/lpc-ich9.c, it indicates something which I didn't find out in the ACPI spec, like FULL_RST (bit 3) and SYS_RST (bit1). Also piix shows similarly(rcr_read/rcr_write). Do you have some ideas on that?

2018-08-02 03:30 UTC, liujing2 commented on hw/i386/virt/acpi.c
> +    if (val & 4) {
Yep, RESET_REG_SUP will be set. Will do it.
Also, I'd like to discuss the RESET_VALUE definition. q35 defines it as 0xf and use 4 to set guest reset. I followed it but this confused me a lot... Of course, we could #define a value, set it to fadt.reset_val and use the #define in write callback.

2018-08-02 09:58 UTC, liujing2 commented on hw/i386/virt/acpi.c
> +        case 5:
OK, will add the _S5 object.

2018-08-06 13:23 UTC, rbradford commented on hw/i386/virt/acpi.c
> +    return d->sleep_control_regs;
Why does it need to read? The specification at no point says the bits need to be unchanged.

2018-08-06 13:26 UTC, rbradford commented on hw/i386/virt/acpi.c
> +    if (val & 4) {
For RESET_REG you can choose any value provided you advertise it correctly in the FADT.

2018-08-07 03:39 UTC, liujing2 commented on hw/i386/virt/acpi.c
> +    return d->sleep_control_regs;
The same to you. I didn't find any spec about the read operations. hmm, this could be done by changing OVMF implementation as follows. But in this way, OVMF can not show clearly what the bits are for. 

```
--- a/OvmfPkg/Library/ResetSystemLib/ResetSystemLib.c
+++ b/OvmfPkg/Library/ResetSystemLib/ResetSystemLib.c
@@ -62,8 +62,7 @@ AcpiSleepControl (

   AcpiReducedPort = 0x3B0;

-  IoBitFieldWrite16 (AcpiReducedPort, 2, 5, (UINT16) SuspendType);
-  IoOr16 (AcpiReducedPort, BIT5);
+  IoWrite16(AcpiReducedPort, BIT2 | BIT4 | BIT5);
   CpuDeadLoop ();
```

2018-08-07 06:26 UTC, liujing2 commented on include/hw/acpi/reduced.h
> +#define ACPI_REDUCED_SLEEP_ENABLE 0x0020 /* SLP_EN */
Will change that in the latest codes in PR.

2018-08-07 06:27 UTC, liujing2 commented on hw/i386/virt/acpi.c
> +    if (val & 4) {
Will change the value to a #define

2018-08-07 06:33 UTC, liujing2 commented
@rbradford I have updated all the discussion changes. Thanks!

2018-08-07 11:50 UTC, rbradford commented on hw/i386/virt/acpi.c
> +    return d->sleep_control_regs;
@liujing2 I don't understand your complaint. Reading the value has no benefit. For sleeping you're supposed to write the value from \_S5 into the registere ORed with the enable bit. Because you're not reading that value i'm happy for you to just write SLEEP_LEVEL << 2 | SLEEP_EN into the register. Where in OVMF you #define SLEEP_LEVEL to 5.

2018-08-07 13:02 UTC, liujing2 commented on hw/i386/virt/acpi.c
> +    return d->sleep_control_regs;
OK, updated.
I am finding how to get FADT in OVMF. By gEfiAcpiTableGuid (defined in ACPI spec 5.2.5.2) and EfiGetSystemConfigurationTable(), probably we could get the RSDP firstly... I haven't investigated if we could reuse the function.

2018-08-07 14:48 UTC, rbradford approved these changes
Looks good. How did you test this?

2018-08-07 15:03 UTC, rbradford commented
I've tested this with the OVMF changes. I want some minor changes to those (constants) but this code is lgtm so can be merged.

2018-08-07 15:04 UTC, merged

2018-08-08 02:05 UTC, liujing2 commented
@rbradford  yep, I tested it using OVMF changes.