[WIP]: make hw/ directory configurable
intel/nemu pull request #57
Opened 2018-08-21 07:46 UTC by yangzhon

@sameo @rbradford @mcastelino 

This PR make all files in hw/ directory configurable and make new x86_64_virt-softmmu.mak for virt-i386 platform. With this new platform mak file, we can make specific binary for virt platform.

How to build binary with this new mak file
./configure --target-list=x86_64_virt-softmmu

Currently, there are some compile error because i removed some CONFIG_XXX in the third patch, please help check those patches, especially for the new x86_64_virt-softmmu.mak file, which will be less CONFIG_XXX enabled.

Let me list the current CONFIG_XXX here:
CONFIG_PCI=y
CONFIG_VIRTIO_PCI=y
CONFIG_VIRTIO=y
CONFIG_ACPI=y
CONFIG_ACPI_X86_CORE=y
CONFIG_ACPI_MEMORY_HOTPLUG=y
CONFIG_ACPI_CPU_HOTPLUG=y
CONFIG_APIC=y
CONFIG_IOAPIC=y
CONFIG_MEM_HOTPLUG=y
CONFIG_NVDIMM=y
CONFIG_ACPI_NVDIMM=y
CONFIG_PCIE_PORT=y
CONFIG_PXB=y
CONFIG_VTD=y
CONFIG_AMD_IOMMU=y
CONFIG_SYS_BUS_DEBUG=y
CONFIG_PCI_LITE=y
CONFIG_ACPI_HW_REDUCED=y
CONFIG_9P=y
CONFIG_MMIO_INTERFACE=y
CONFIG_ACPI_X86_CORE=y
CONFIG_VHOST_NET=y
CONFIG_X86_VIRT=y
CONFIG_KVM_CLOCK=y

If there are still some CONFIG_XXX unused in virt platform, please let me know, thanks!

2018-08-21 09:43 UTC, yangzhon commented
Another issue is:

If we add new softmmu file, x86_64_virt-softmmu.mak, we also need  add new target, TARGET_X86_64_VIRT, in some source code files, because those files only support TARGET_X86_64.

2018-08-21 12:05 UTC, rbradford commented
Hi @yangzhon.

Can you work on making your changes in "virt: hw: make files build configurable" more upstreamable. I think at the very least this should involve splitting the changes into more logical changes, commit messages explaining why you're doing that. You should also look around to see if some of the other CONFIG_ options make better sense than adding a new one or even maybe it's work using the boolean conditionals to "and" two config options together.

It is my firm belief that such missing build control of blocks are upstream gaps and so should be readily accepted upstream. As such I think this work should only focus on PC and Q35 directly from the 3.0 tag and then the topic/virt-x86 could be rebased on top of that.

2018-08-22 13:44 UTC, yangzhon commented
@sameo @rbradford @mcastelino

Please review, thanks!

2018-08-23 12:44 UTC, yangzhon commented
Add new x86_64_virt-softmmu build and TARGET_X86_64=y for all default TARGET_X86_64 build.

2018-08-24 12:03 UTC, yangzhon commented
@sameo @rbradford @mcastelino

The patchset made hw/ directory configurable and the pc/q35 platform code can be compiled out of virt binary. The minimal x86_64_virt-softmmu.mak is still on the way, and there are lots of work to do.

There are two unclear issues
(1). x86_64_virt-softmmu.mak will be minimal mak file, from current USB porting, i found we also need add --disable-usb during the configure command.   This will result in another issue, if the customer use the ./configure to do full build, which will generate errors in virt platform build because minimal virt mak file need co-work with some "--disable-xxx" commands.
(2) about the VGA
There are some kinds of VGA, which kind of VGA will be supported ? vfio-vga, pci-vga and virtio-vga?

2018-08-24 16:23 UTC, rbradford commented
@yangzhon virt platform will not support USB or VGA.

2018-08-24 19:06 UTC, rbradford requested changes

2018-08-24 19:06 UTC, rbradford commented on default-configs/hw-common.mak
> +CONFIG_9P_FS=y
There is no need for this. 9pfs is already controlled by:

in hw/Makefile.objs:

```
devices-dirs-$(call land,$(CONFIG_VIRTFS),$(call lor,$(CONFIG_VIRTIO),$(CONFIG_XEN))) += 9pfs/
```

2018-08-24 19:06 UTC, rbradford commented on default-configs/hw-common.mak
> +CONFIG_BLOCK=y
block.c is needed for everyone so I don't think it ever makes sense to make this conditional.

2018-08-24 19:06 UTC, rbradford commented on default-configs/hw-common.mak
> +CONFIG_UNIMP_DEV=y
I think this should be CONFIG_UNIMPLEMENTED

2018-08-24 19:06 UTC, rbradford commented on default-configs/hw-common.mak
> +CONFIG_PCI_SHPC=y
I don't think this should be in hw-common.mak. Only in those files that use CONFIG_PCI=y

2018-08-24 19:06 UTC, rbradford commented on hw/pcmcia/Makefile.objs
> -common-obj-y += pcmcia.o
You should make this change at the hw/Makefile.objs level.

2018-08-24 19:06 UTC, rbradford commented on default-configs/hw-common.mak
> +CONFIG_PCMCIA=y
This shouldn't be here. pcmcia.c is a very basic object definition. You should put this in the config file where CONFIG_PXA2XX is turned on

2018-08-24 19:06 UTC, rbradford commented on hw/bt/Makefile.objs
> +common-obj-$(CONFIG_BT) += core.o l2cap.o sdp.o hci.o hid.o
I think CONFIG_BLUEZ from the configure script should be used instead.

2018-08-24 19:06 UTC, rbradford commented on default-configs/hw-common.mak
> +CONFIG_PS2_DEV=y
This should only be on targets that only need it...I guess only for x86_64 and i386.

2018-08-24 19:06 UTC, rbradford commented on default-configs/hw-common.mak
> +CONFIG_HID_DEV=y
Would be worth looking around what this virtual device is used for.

2018-08-24 19:06 UTC, rbradford commented on hw/nvram/Makefile.objs
> +common-obj-$(CONFIG_93XX_EEPROM) += eeprom93xx.o
This is used by a few virtual devices. You should grep the source code and OR them rather than creating a new one.

2018-08-24 19:06 UTC, rbradford commented on hw/nvram/Makefile.objs
> +common-obj-$(CONFIG_NVRAM) += chrp_nvram.o
Ditto. This is used by just a few other virtual devices so you don't need to add a new config option.

2018-08-24 19:06 UTC, rbradford commented on default-configs/hw-common.mak
> +CONFIG_CDROM=y
I think you will also need to add checks to vl.c to handle this not being present.

2018-08-24 19:06 UTC, rbradford commented on default-configs/i386-softmmu.mak
> +CONFIG_ACPI_X86_PIXX=y
I think adding a CONFIG_X86_PIIX would be better.

2018-08-24 19:06 UTC, rbradford commented on hw/acpi/Makefile.objs
> +common-obj-$(CONFIG_ACPI_X86_PIXX) += piix4.o pcihp.o
And then CONFIG_ACPI_X86 && CONFIG_X86_PIIX

2018-08-24 19:06 UTC, rbradford commented on hw/audio/Makefile.objs
> +common-obj-$(CONFIG_AUDIO) += soundhw.o
Just removing this will break vl.c.

2018-08-24 19:06 UTC, rbradford commented on hw/cpu/Makefile.objs
> +common-obj-$(CONFIG_ARM_CORE) += core.o
There is nothing ARM specific about this. This file should always be included in the build and not made conditional

2018-08-24 19:06 UTC, rbradford commented on hw/intc/Makefile.objs
> +common-obj-$(CONFIG_INT_CTRL) += intc.o
This a trivial file. There is no harm in always including it.

2018-08-24 19:06 UTC, rbradford commented on default-configs/hw-common.mak
> +CONFIG_PCI_BRIDGE=y
What platforms actually need this PCI-PCI bridge?

2018-08-24 19:06 UTC, rbradford commented on hw/pci-host/Makefile.objs
> +common-obj-$(CONFIG_PAM) += pam.o
Use an OR of CONFIG_Q35 and CONFIG_PIIX (only files that use it)

2018-08-24 19:06 UTC, rbradford commented on default-configs/hw-common.mak
> +CONFIG_SCSI=y
Already in many config files.

2018-08-24 19:06 UTC, rbradford commented on hw/scsi/Makefile.objs
> +common-obj-$(CONFIG_SCSI) += scsi-generic.o scsi-bus.o
Handled already in hw/Makefile.objs
```
devices-dirs-$(CONFIG_SCSI) += scsi/
```

2018-09-06 13:29 UTC, sameo commented on default-configs/hw-common.mak
> +CONFIG_PCI_SHPC=y
Agreed. It should be in pci.mak imho.

2018-09-06 13:36 UTC, sameo commented on default-configs/x86_64_virt-softmmu.mak
> +CONFIG_X86_PC_Q35_ACPI_BUILD=y
This one should be a lot shorter, something along those lines:

```
# Default configuration for x86_64_virt-softmmu

# PCI config
CONFIG_PCI=y
CONFIG_PCI_BRIDGE=y
CONFIG_SERIAL=y
CONFIG_SERIAL_PCI=y
CONFIG_NVME_PCI=y

# virtio and vhost
CONFIG_VIRTIO=y
CONFIG_VIRTIO_9P=y
CONFIG_VIRTIO_BALLOON=y
CONFIG_VIRTIO_BLK=y
CONFIG_VIRTIO_CRYPTO=y
CONFIG_VIRTIO_GPU=y
CONFIG_VIRTIO_INPUT=y
CONFIG_VIRTIO_NET=y
CONFIG_VIRTIO_RNG=y
CONFIG_VIRTIO_SCSI=y
CONFIG_VIRTIO_SERIAL=y
CONFIG_VIRTIO_PCI=y
CONFIG_VHOST_NET=y
CONFIG_VHOST_SCSI=y
CONFIG_VHOST_USER_SCSI=$(call land,$(CONFIG_VHOST_USER),$(CONFIG_LINUX))
CONFIG_VHOST_USER_BLK=$(call land,$(CONFIG_VHOST_USER),$(CONFIG_LINUX))

# HW common
CONFIG_9P_FS=y
CONFIG_BLOCK=y
CONFIG_CDROM=y
CONFIG_HARD_DISK=y
CONFIG_NVRAM=y
CONFIG_INT_CTRL=y
CONFIG_SCSI=y
CONFIG_TPM_UTIL=y

# Others
CONFIG_ACPI=y
CONFIG_ACPI_X86_CORE=y
CONFIG_ACPI_MEMORY_HOTPLUG=y
CONFIG_ACPI_CPU_HOTPLUG=y
CONFIG_APIC=y
CONFIG_IOAPIC=y
CONFIG_MEM_HOTPLUG=y
CONFIG_NVDIMM=y
CONFIG_ACPI_NVDIMM=y
CONFIG_PCIE_PORT=y
CONFIG_PXB=y
CONFIG_VTD=y
CONFIG_AMD_IOMMU=y
CONFIG_SYS_BUS_DEBUG=y
CONFIG_PCI_LITE=y
CONFIG_ACPI_HW_REDUCED=y
CONFIG_9P=y
CONFIG_MMIO_INTERFACE=y
CONFIG_ACPI_X86_CORE=y
CONFIG_X86_VIRT=y
CONFIG_KVM_CLOCK=y
CONFIG_KVM_VAPIC=y
```

2018-09-07 08:13 UTC, yangzhon commented
@sameo @rbradford @mcastelino

I submitted one NEW PR #80 to replace this older one, drop this one, thanks!

2018-09-07 08:13 UTC, closed without merging