[WIP]: make device emulation files configurable in hw directory
intel/nemu pull request #80
Opened 2018-09-07 08:11 UTC by yangzhon

@sameo @rbradford @mcastelino

This PR make all files in hw/ directory configurable and make new x86_64_virt-softmmu.mak for virt-i386 platform. With this new platform mak file, we can make specific binary for virt platform.

How to build binary with this new mak file
./configure --target-list=x86_64_virt-softmmu

The FULL build will omit x86_64_virt-softmmu build and virt platform will be still compiled into x86_64-softmmu binary.

Currently, there are some compile errors because i removed some CONFIG_XXX in the third patch, please help check those patches, especially for the new x86_64_virt-softmmu.mak file, which will be less CONFIG_XXX enabled.

# Default configuration for x86_64_virt-softmmu
CONFIG_VHOST_USER_SCSI=$(call land,$(CONFIG_VHOST_USER),$(CONFIG_LINUX))
CONFIG_VHOST_USER_BLK=$(call land,$(CONFIG_VHOST_USER),$(CONFIG_LINUX))

CONFIG_PCI=y
CONFIG_SCSI=y
CONFIG_BLOCK=y
CONFIG_NVME_PCI=y

CONFIG_VIRTIO=y
CONFIG_VIRTIO_9P=y
CONFIG_VIRTIO_BALLOON=y
CONFIG_VIRTIO_BLK=y
CONFIG_VIRTIO_CRYPTO=y
CONFIG_VIRTIO_GPU=y
CONFIG_VIRTIO_INPUT=y
CONFIG_VIRTIO_NET=y
CONFIG_VIRTIO_RNG=y
CONFIG_VIRTIO_SCSI=y
CONFIG_VIRTIO_SERIAL=y
CONFIG_VIRTIO_PCI=y

CONFIG_ACPI=y
CONFIG_ACPI_X86=y
CONFIG_APIC=y
CONFIG_IOAPIC=y
CONFIG_NVDIMM=y
CONFIG_ACPI_NVDIMM=y
CONFIG_VTD=y
CONFIG_AMD_IOMMU=y
CONFIG_SYS_BUS_DEBUG=y
CONFIG_PCI_LITE=y
CONFIG_ACPI_HW_REDUCED=y
CONFIG_X86_VIRT=y
CONFIG_MEM_HOTPLUG=y
CONFIG_ACPI_MEMORY_HOTPLUG=y
CONFIG_ACPI_CPU_HOTPLUG=y
CONFIG_ACPI_PCI_HOTPLUG=y

CONFIG_PFLASH_CFI01=y
CONFIG_HARD_DISK=y

2018-09-07 08:20 UTC, yangzhon commented
@sameo ,

The build is almost be successfully done now and there are two issues with FULL build and virt target build
(1) FULL build  ---> this issue is caused by moving fw_build_smbios() to hw/smbios/smbios.c file
/home/chen/94/nemu/hw/smbios/smbios.c:1140:5: error: unknown type name ‘X86CPU’; did you mean ‘CPU’?
     X86CPU *cpu = X86_CPU(ms->possible_cpus->cpus[0].cpu);
     ^~~~~~
     CPU
/home/chen/94/nemu/hw/smbios/smbios.c:1140:19: error: implicit declaration of function ‘X86_CPU’; did you mean ‘BP_CPU’? [-Werror=implicit-function-declaration]
     X86CPU *cpu = X86_CPU(ms->possible_cpus->cpus[0].cpu);

(2) virt build
../qapi/qapi-commands-run-state.o: In function `qmp_marshal_watchdog_set_action':
/home/chen/nemu/build/qapi/qapi-commands-run-state.c:104: undefined reference to `qmp_watchdog_set_action'

2018-09-10 12:58 UTC, sameo commented
@yangzhon With the following configure script:

```shell
#!/bin/bash
set -e

if [[ "$EXTRA_CFLAGS" == "" ]]; then
    EXTRA_CFLAGS=" -O3 -fno-semantic-interposition -falign-functions=32 -D_FORTIFY_SOURCE=2 -fPIE"
fi

../configure \
 --disable-fdt \
 --disable-libiscsi \
 --disable-libnfs \
 --disable-libssh2 \
 --disable-linux-aio \
 --disable-lzo \
 --disable-modules \
 --disable-netmap \
 --disable-qom-cast-debug \
 --disable-seccomp \
 --disable-snappy \
 --disable-tcmalloc \
 --disable-tools \
 --disable-tpm \
 --disable-virtfs \
 --disable-tcg \
 --disable-slirp \
 --disable-capstone \
 --enable-attr \
 --enable-cap-ng \
 --enable-kvm \
 --enable-rbd \
 --enable-vhost-crypto \
 --enable-vhost-net \
 --enable-vhost-scsi \
 --enable-vhost-user \
 --enable-vhost-vsock \
 --enable-virtfs \
 --target-list=x86_64_virt-softmmu \
 --extra-cflags="$EXTRA_CFLAGS" \
 --extra-ldflags=" -pie -z noexecstack -z relro -z now" \
 --libdir=/usr/lib64/nemu \
 --libexecdir=/usr/libexec/nemu \
 --datadir=/usr/share/nemu

```

The build passes.

2018-09-10 15:41 UTC, sameo commented
With a few ugly fixes, I can build and boot a CL image on top of virt. The new device model still needs some work, but looks saner than the vanilla one:

```
(qemu) info qdm
Controller/Bridge/Hub devices:
name "pci-lite-host", bus System, no-user
name "vfio-pci-igd-lpc-bridge", bus PCI, desc "VFIO dummy ISA/LPC bridge for IGD assignment"

Storage devices:
name "cfi.pflash01", bus System, no-user
name "nvme", bus PCI, desc "Non-Volatile Memory Express"
name "scsi-block", bus SCSI, desc "SCSI block device passthrough"
name "scsi-cd", bus SCSI, desc "virtual SCSI CD-ROM"
name "scsi-disk", bus SCSI, desc "virtual SCSI disk or CD-ROM (legacy)"
name "scsi-generic", bus SCSI, desc "pass through generic scsi device (/dev/sg*)"
name "scsi-hd", bus SCSI, desc "virtual SCSI disk"
name "vhost-scsi", bus virtio-bus
name "vhost-scsi-pci", bus PCI
name "vhost-user-blk", bus virtio-bus
name "vhost-user-blk-pci", bus PCI
name "vhost-user-scsi", bus virtio-bus
name "vhost-user-scsi-pci", bus PCI
name "virtio-9p-device", bus virtio-bus
name "virtio-9p-pci", bus PCI, alias "virtio-9p"
name "virtio-blk-device", bus virtio-bus
name "virtio-blk-pci", bus PCI, alias "virtio-blk"
name "virtio-scsi-device", bus virtio-bus
name "virtio-scsi-pci", bus PCI, alias "virtio-scsi"

Network devices:
name "virtio-net-device", bus virtio-bus
name "virtio-net-pci", bus PCI, alias "virtio-net"

Input devices:
name "virtconsole", bus virtio-serial-bus
name "virtio-input-host-device", bus virtio-bus
name "virtio-input-host-pci", bus PCI, alias "virtio-input-host"
name "virtio-keyboard-device", bus virtio-bus
name "virtio-keyboard-pci", bus PCI, alias "virtio-keyboard"
name "virtio-mouse-device", bus virtio-bus
name "virtio-mouse-pci", bus PCI, alias "virtio-mouse"
name "virtio-serial-device", bus virtio-bus
name "virtio-serial-pci", bus PCI, alias "virtio-serial"
name "virtio-tablet-device", bus virtio-bus
name "virtio-tablet-pci", bus PCI, alias "virtio-tablet"
name "virtserialport", bus virtio-serial-bus

Display devices:
name "virtio-gpu-device", bus virtio-bus
name "virtio-gpu-pci", bus PCI, alias "virtio-gpu"

Misc devices:
name "sysbus-debugcon", bus System
name "vfio-pci", bus PCI, desc "VFIO-based PCI device assignment"
name "vhost-vsock-device", bus virtio-bus
name "vhost-vsock-pci", bus PCI
name "virtio-balloon-device", bus virtio-bus
name "virtio-balloon-pci", bus PCI, alias "virtio-balloon"
name "virtio-crypto-device", bus virtio-bus
name "virtio-crypto-pci", bus PCI
name "virtio-rng-device", bus virtio-bus
name "virtio-rng-pci", bus PCI, alias "virtio-rng"

CPU devices:
name "486-x86_64-cpu"
name "athlon-x86_64-cpu"
name "base-x86_64-cpu"
name "Broadwell-IBRS-x86_64-cpu"
name "Broadwell-noTSX-IBRS-x86_64-cpu"
name "Broadwell-noTSX-x86_64-cpu"
name "Broadwell-x86_64-cpu"
name "Conroe-x86_64-cpu"
name "core2duo-x86_64-cpu"
name "coreduo-x86_64-cpu"
name "EPYC-IBPB-x86_64-cpu"
name "EPYC-x86_64-cpu"
name "Haswell-IBRS-x86_64-cpu"
name "Haswell-noTSX-IBRS-x86_64-cpu"
name "Haswell-noTSX-x86_64-cpu"
name "Haswell-x86_64-cpu"
name "host-x86_64-cpu"
name "IvyBridge-IBRS-x86_64-cpu"
name "IvyBridge-x86_64-cpu"
name "KnightsMill-x86_64-cpu"
name "kvm32-x86_64-cpu"
name "kvm64-x86_64-cpu"
name "max-x86_64-cpu"
name "n270-x86_64-cpu"
name "Nehalem-IBRS-x86_64-cpu"
name "Nehalem-x86_64-cpu"
name "Opteron_G1-x86_64-cpu"
name "Opteron_G2-x86_64-cpu"
name "Opteron_G3-x86_64-cpu"
name "Opteron_G4-x86_64-cpu"
name "Opteron_G5-x86_64-cpu"
name "Penryn-x86_64-cpu"
name "pentium-x86_64-cpu"
name "pentium2-x86_64-cpu"
name "pentium3-x86_64-cpu"
name "phenom-x86_64-cpu"
name "qemu32-x86_64-cpu"
name "qemu64-x86_64-cpu"
name "SandyBridge-IBRS-x86_64-cpu"
name "SandyBridge-x86_64-cpu"
name "Skylake-Client-IBRS-x86_64-cpu"
name "Skylake-Client-x86_64-cpu"
name "Skylake-Server-IBRS-x86_64-cpu"
name "Skylake-Server-x86_64-cpu"
name "Westmere-IBRS-x86_64-cpu"
name "Westmere-x86_64-cpu"

Uncategorized devices:
name "amd-iommu", bus System
name "AMDVI-PCI", bus PCI
name "apic", no-user
name "fw_cfg_io", bus System, no-user
name "fw_cfg_mem", bus System, no-user
name "intel-iommu", bus System
name "ioapic", bus System, no-user
name "kvm-apic", no-user
name "kvm-ioapic", bus System, no-user
name "kvmclock", bus System, no-user
name "kvmvapic", bus System, no-user
name "loader", desc "Generic Loader"
name "migration", no-user
name "mmio_interface", no-user
name "nvdimm", desc "DIMM memory module"
name "or-irq", no-user
name "pc-dimm", desc "DIMM memory module"
name "pci-lite-device", bus PCI, desc "Host bridge", no-user
name "qemu,register", no-user
name "split-irq", no-user
name "virt-acpi", bus System, desc "ACPI", no-user
```

2018-09-10 22:47 UTC, sameo commented on hw/i386/virt/stub.c
> +}
Those stubs should be defined e.g. under `hw/vfio/stub.c` and only built when `CONFIG_VFIO_VGA` is not defined. They are not virt specific, and thus will be needed by anyone disabling `CONFIG_VFIO_VGA`.

2018-09-10 23:02 UTC, sameo commented
@yangzhon A few comments on this PR:

1. We need to move all the stubs into their own subsystem. See e.g. https://github.com/intel/nemu/pull/80/commits/1be5d66369f13d64c52b0b6bbe48ec765a95b853#r216498770.

2. We need to keep only non platform specific ACPI routines into `hw/i386/acpi-build.c` and move machine type specific ones into their respective machine types files. We should always build acpi-build.c.

3. When looking at the resulting device model, I see a few devices that could be still removed:

```
name "vfio-pci-igd-lpc-bridge", bus PCI, desc "VFIO dummy ISA/LPC bridge for IGD assignment"
name "virtio-input-host-device", bus virtio-bus
name "virtio-input-host-pci", bus PCI, alias "virtio-input-host"
name "virtio-keyboard-device", bus virtio-bus
name "virtio-keyboard-pci", bus PCI, alias "virtio-keyboard"
name "virtio-mouse-device", bus virtio-bus
name "virtio-mouse-pci", bus PCI, alias "virtio-mouse"
name "virtio-tablet-device", bus virtio-bus
name "virtio-tablet-pci", bus PCI, alias "virtio-tablet"
name "virtserialport", bus virtio-serial-bus
```

So we should also add some patches to configure them out.

4. Some devices presence should be discussed:

```
name "cfi.pflash01", bus System, no-user
name "scsi-block", bus SCSI, desc "SCSI block device passthrough"
name "scsi-cd", bus SCSI, desc "virtual SCSI CD-ROM"
name "scsi-disk", bus SCSI, desc "virtual SCSI disk or CD-ROM (legacy)"
name "scsi-generic", bus SCSI, desc "pass through generic scsi device (/dev/sg*)"
name "scsi-hd", bus SCSI, desc "virtual SCSI disk"
name "virtio-gpu-device", bus virtio-bus
name "virtio-gpu-pci", bus PCI, alias "virtio-gpu"
```

2018-09-10 23:14 UTC, mcastelino commented on default-configs/x86_64_virt-softmmu.mak
> +CONFIG_MEM_HOTPLUG=y
Does hotplug have to be enabled by default?

2018-09-10 23:17 UTC, mcastelino commented on default-configs/x86_64_virt-softmmu.mak
> +CONFIG_NVDIMM=y
Same with NVDIMM. Do we need this to be enabled by default.

2018-09-11 05:33 UTC, yangzhon commented on hw/i386/virt/stub.c
> +}
@sameo 

Yes, thanks, i will do ti.

2018-09-11 05:38 UTC, yangzhon commented
@sameo 

name "kvmvapic", bus System, no-user

We do not need kvmvapic, which is only used in older amd chips and older windows xp system.

2018-09-11 05:43 UTC, yangzhon commented
@sameo @rbradford @mcastelino




We need to define minimal device models for virt platform, and we can do porting per this target.

By the way, the display in VFIO and some legacy devices in virtio will need split files to get those device models compiled out.

The total device models in virt platform is around 67, the device model in Microsoft is around 20, the gap is 47.

2018-09-11 06:29 UTC, yangzhon commented
@sameo 

As for 2) 
We need to keep only non platform specific ACPI routines into hw/i386/acpi-build.c and move machine type specific ones into their respective machine types files. We should always build acpi-build.c.

In fact, only build_madt() in hw/i386/acpi-build.c will be called by virt platform and other code are related with PC and Q35. whether need we split this to three files ? acpi-build-core.c, acpi-build-piix.c and acpi-build-q35.c ?  which can make the code more cleaner if we do virt build. thanks!

2018-09-11 09:04 UTC, sameo commented
@yangzhon 
> acpi-build-core.c, acpi-build-piix.c and acpi-build-q35.c ? which can make the code more cleaner if we do virt build. thanks!

I'm fine with that option as well.

2018-09-11 09:17 UTC, sameo commented
@yangzhon 
> The total device models in virt platform is around 67

We have most of the virtio devices duplicated between `virtio-foo` and `virtio-foo-pci`. Not sure how we should count here.

2018-09-11 09:20 UTC, rbradford commented
@sameo count them once as the non -pci suffix version is just an alias.

2018-09-11 09:26 UTC, sameo commented
@yangzhon 
> We do not need kvmvapic, which is only used in older amd chips and older windows xp system.

When booting with CONFIG_KVM_VAPIC turned off:

```
qemu-system-x86_64_virt: Unknown device 'kvmvapic' for default sysbus
```

I'll investigate further.

2018-09-11 09:29 UTC, sameo commented
@yangzhon We're down to 46 when removing the PCI aliases.

2018-09-11 12:10 UTC, yangzhon commented
@sameo @rbradford @mcastelino

In the upstreamed qemu:
one by one to count: total 245 device model.
count by rob's method:  228 device model.

2018-09-11 12:32 UTC, yangzhon commented
#define TYPE_VIRTIO_CONSOLE_SERIAL_PORT "virtserialport"
static const TypeInfo virtconsole_info = {
    .name          = "virtconsole",
    .parent        = TYPE_VIRTIO_CONSOLE_SERIAL_PORT,
    .class_init    = virtconsole_class_init,
};

So we need keep virtserialport device model
name "virtserialport", bus virtio-serial-bus

2018-09-12 02:21 UTC, yangzhon commented on default-configs/x86_64_virt-softmmu.mak
> +CONFIG_MEM_HOTPLUG=y
@mcastelino,

If we also need compile out CPU and ACPI PCI hotplug? If like this, we will not support any hotplug. thanks!

2018-09-12 02:25 UTC, yangzhon commented
@sameo,

The total device model number related IRQ is 7,
name "apic", no-user
name "ioapic", bus System, no-user
name "kvm-apic", no-user
name "kvm-ioapic", bus System, no-user
name "kvmvapic", bus System, no-user
name "or-irq", no-user
name "split-irq", no-user

below device model have been compiled out by me and samuel
name "kvmvapic", bus System, no-user
name "or-irq", no-user
name "split-irq", no-user

2018-09-12 03:27 UTC, yangzhon commented
@sameo 

more patches uploaded.

Now the new info qdm as below
Controller/Bridge/Hub devices:
name "pci-lite-host", bus System, no-user
name "vfio-pci-igd-lpc-bridge", bus PCI, desc "VFIO dummy ISA/LPC bridge for IGD assignment"

Storage devices:
name "cfi.pflash01", bus System, no-user
name "nvme", bus PCI, desc "Non-Volatile Memory Express"
name "scsi-block", bus SCSI, desc "SCSI block device passthrough"
name "scsi-cd", bus SCSI, desc "virtual SCSI CD-ROM"
name "scsi-disk", bus SCSI, desc "virtual SCSI disk or CD-ROM (legacy)"
name "scsi-generic", bus SCSI, desc "pass through generic scsi device (/dev/sg*)"
name "scsi-hd", bus SCSI, desc "virtual SCSI disk"
name "vhost-scsi", bus virtio-bus
name "vhost-scsi-pci", bus PCI
name "vhost-user-blk", bus virtio-bus
name "vhost-user-blk-pci", bus PCI
name "vhost-user-scsi", bus virtio-bus
name "vhost-user-scsi-pci", bus PCI
name "virtio-9p-device", bus virtio-bus
name "virtio-9p-pci", bus PCI, alias "virtio-9p"
name "virtio-blk-device", bus virtio-bus
name "virtio-blk-pci", bus PCI, alias "virtio-blk"
name "virtio-scsi-device", bus virtio-bus
name "virtio-scsi-pci", bus PCI, alias "virtio-scsi"

Network devices:
name "virtio-net-device", bus virtio-bus
name "virtio-net-pci", bus PCI, alias "virtio-net"

Input devices:
name "virtconsole", bus virtio-serial-bus
name "virtio-serial-device", bus virtio-bus
name "virtio-serial-pci", bus PCI, alias "virtio-serial"
name "virtserialport", bus virtio-serial-bus

Misc devices:
name "sysbus-debugcon", bus System
name "vfio-pci", bus PCI, desc "VFIO-based PCI device assignment"
name "vhost-vsock-device", bus virtio-bus
name "vhost-vsock-pci", bus PCI
name "virtio-balloon-device", bus virtio-bus
name "virtio-balloon-pci", bus PCI, alias "virtio-balloon"
name "virtio-crypto-device", bus virtio-bus
name "virtio-crypto-pci", bus PCI
name "virtio-rng-device", bus virtio-bus
name "virtio-rng-pci", bus PCI, alias "virtio-rng"

Uncategorized devices:
name "apic", no-user
name "fw_cfg_io", bus System, no-user
name "fw_cfg_mem", bus System, no-user
name "intel-iommu", bus System
name "ioapic", bus System, no-user
name "kvm-apic", no-user
name "kvm-ioapic", bus System, no-user
name "kvmclock", bus System, no-user
name "kvmvapic", bus System, no-user
name "loader", desc "Generic Loader"
name "migration", no-user
name "mmio_interface", no-user
name "pc-dimm", desc "DIMM memory module"
name "pci-lite-device", bus PCI, desc "Host bridge", no-user
name "virt-acpi", bus System, desc "ACPI", no-user

The total device model number in my side is 40. 

Let me do specific stub function and split acpi-build.c in this afternoon.

2018-09-12 11:05 UTC, yangzhon commented
@sameo,

The updated PR include
(1) Rebase to latest code
(2) Remove hw/i386/virt/stub.c file and move stub function to each directory in hw/

2018-09-12 23:55 UTC, sameo commented
@yangzhon I just pushed 3 commits to make the IGD in particular and the VFIO PCI quirks in general configurable as well. This is a WIP as it only extracts IGD out for now, but qdm shows the device is gone.
I need to add the new VFIO_PCI_QUIRKS default options to hw-common.mak.

2018-09-15 09:09 UTC, yangzhon commented
@sameo ,

I have merged the VFIO full build patch into your patch, so you don't need change any more.
I have removed WIP from this PR, please help review. thanks!

2018-09-16 13:18 UTC, sameo requested changes
Carried some of Rob's comments from PR #57

2018-09-16 13:18 UTC, sameo commented on default-configs/hw-common.mak
> +CONFIG_BLOCK=y
`BLOCK` will be needed by everyone, I think we can remove that one.

2018-09-16 13:18 UTC, sameo commented on hw/misc/Makefile.objs
> +common-obj-$(CONFIG_UNIMP_DEV) += unimp.o
Could we please rename that one to `CONFIG_UNIMPLEMENTED` ?

2018-09-16 13:18 UTC, sameo commented on hw/nvram/Makefile.objs
> +common-obj-$(CONFIG_93XX_EEPROM) += eeprom93xx.o
Only 2 devices are depending on this one: esp-pci and eepro100. So we should use:

```
common-obj-$(call lor,$(CONFIG_EEPRO100_PCI),$(CONFIG_ESP_PCI)) += eepprom93xx.o
```

And  avoid carrying an additional `CONFIG_` knob.

2018-09-16 13:18 UTC, sameo commented on hw/nvram/Makefile.objs
> +common-obj-$(CONFIG_NVRAM) += chrp_nvram.o
Same for that one, it's only used by a few devices/platforms. And avoid creating `CONFIG_NVRAM`.

2018-09-16 13:18 UTC, sameo commented on hw/acpi/Makefile.objs
> +common-obj-$(CONFIG_ACPI_X86_PIXX) += piix4.o
Typo: `CONFIG_ACPI_X86_PIIX`, not `PIXX`

2018-09-16 13:18 UTC, sameo commented on default-configs/mips-softmmu-common.mak
> +CONFIG_ACPI_X86_PIXX=y
Why does MIPS need an x86 specific ACPI configuration?

2018-09-16 13:18 UTC, sameo commented on hw/cpu/Makefile.objs
> +common-obj-$(CONFIG_ARM_CORE) += core.o
Maybe this file is only used by ARM builds, but there's nothing ARM specific in there.
Having a more generic configuration name like `CONFIG_CPU_DEVICE` would be better.

2018-09-16 13:21 UTC, sameo commented on default-configs/x86_64_virt-softmmu.mak
> -CONFIG_VIRTIO_GPU=y
Could we please squash that one into e4e0fe01b9c994a4deeacf0d53fdf75edf302217 ?

2018-09-17 08:06 UTC, yangzhon commented
@sameo @rbradford @mcastelino

name "apic", no-user
name "ioapic", bus System, no-user
name "kvm-apic", no-user
name "kvm-ioapic", bus System, no-user

The IRQ related device model, we will offload the IRQs emulation to KVM side, so at least "IOAPIC" is not needed anymore.   I will do this in next NEW PR.

2018-09-17 08:37 UTC, yangzhon commented on default-configs/hw-common.mak
> +CONFIG_BLOCK=y
thanks, this file is built-in file for all platform. I will remove this CONFIG.

2018-09-17 09:27 UTC, yangzhon commented on hw/misc/Makefile.objs
> +common-obj-$(CONFIG_UNIMP_DEV) += unimp.o
Done, thanks!

2018-09-17 10:34 UTC, yangzhon commented on hw/nvram/Makefile.objs
> +common-obj-$(CONFIG_93XX_EEPROM) += eeprom93xx.o
Done, thanks for review.

2018-09-17 10:49 UTC, yangzhon commented on hw/nvram/Makefile.objs
> +common-obj-$(CONFIG_NVRAM) += chrp_nvram.o
@sameo ,

Mac_nvram.c (hw\nvram):    sysp_end = chrp_nvram_create_system_partition(&nvr->data[off],
Spapr_nvram.c (hw\nvram):        chrp_nvram_create_system_partition(nvram->buf, MIN_NVRAM_SIZE / 4);
Sun4m.c (hw\sparc):    sysp_end = chrp_nvram_create_system_partition(image, 0);
Sun4u.c (hw\sparc64):    sysp_end = chrp_nvram_create_system_partition(image, 0);

Sun4m.c and Sun4u.c are all built-in files, if chrp_nvram.c base on platform, we need extra two CONFIGs for this.

2018-09-17 10:58 UTC, yangzhon commented on hw/acpi/Makefile.objs
> +common-obj-$(CONFIG_ACPI_X86_PIXX) += piix4.o
It's my stupid error, thanks!

2018-09-17 11:03 UTC, yangzhon commented on default-configs/mips-softmmu-common.mak
> +CONFIG_ACPI_X86_PIXX=y
@sameo ,

Please check below functions,
Mips_malta.c (hw\mips):    smbus = piix4_pm_init(pci_bus, piix4_devfn + 3, 0x1100,
Pc.h (include\hw\i386):I2CBus *piix4_pm_init(PCIBus *bus, int devfn, uint32_t smb_io_base,
Pc_piix.c (hw\i386):        smbus = piix4_pm_init(pci_bus, piix3_devfn + 3, 0xb100,
Piix4.c (hw\acpi):I2CBus *piix4_pm_init(PCIBus *bus, int devfn, uint32_t smb_io_base,


mips call piix4_pm_init(), which is defined in PIIX code, thanks!

2018-09-17 12:15 UTC, yangzhon commented on default-configs/mips-softmmu-common.mak
> +CONFIG_ACPI_X86_PIXX=y
@sameo 

Sorry, i made a mistake. mips called  piix4_pm_init(), which is defined in Pc_piix.c, not Piix4.c.

So CONFIG_ACPI_X86_PIXX=y need remove, thanks!

2018-09-17 13:07 UTC, yangzhon commented on hw/nvram/Makefile.objs
> +common-obj-$(CONFIG_93XX_EEPROM) += eeprom93xx.o
@sameo 
when i used common-obj-$(call lor,$(CONFIG_EEPRO100_PCI),$(CONFIG_ESP_PCI)) += eepprom93xx.o

and do full build, the arm will report below issue
make: *** No rule to make target 'hw/nvram/eepprom93xx.o', needed by 'subdir-aarch64-softmmu'.  Stop.

In fact, CONFIG_EEPRO100_PCI and CONFIG_ESP_PCI have been defined in device.mak file

2018-09-17 13:35 UTC, yangzhon commented on default-configs/x86_64_virt-softmmu.mak
> -CONFIG_VIRTIO_GPU=y
@sameo,

Done, thanks!

2018-09-17 13:51 UTC, sameo commented on default-configs/mips-softmmu-common.mak
> +CONFIG_ACPI_X86_PIXX=y
I see that the Malta boards are running with a piix4 chipset(!), my bad.
So then it would feel better to add `CONFIG_X86_PIIX` to the MIPS Malta config, and then `land($CONFIG_ACPI_X86, $CONFIG_X86_PIIX) in the `acpi/Makefile.objs` makefile for the piix4.o object.

2018-09-17 14:02 UTC, sameo commented on hw/nvram/Makefile.objs
> +common-obj-$(CONFIG_NVRAM) += chrp_nvram.o
Ok, then let's keep that CONFIG but rename it to `CONFIG_CHRP_NVRAM`. And add it to the sparc and sparc64 .mak files.

2018-09-17 14:47 UTC, sameo requested changes

2018-09-17 14:47 UTC, sameo commented on hw/vfio/stub.c
> + * QEMU i386 virt Platform stub
This is the VFIO stubs, not the virt platform one.

2018-09-18 05:51 UTC, yangzhon commented on hw/nvram/Makefile.objs
> +common-obj-$(CONFIG_NVRAM) += chrp_nvram.o
Done, thanks!

2018-09-18 05:53 UTC, yangzhon commented on default-configs/mips-softmmu-common.mak
> +CONFIG_ACPI_X86_PIXX=y
Done, thanks!

2018-09-18 05:53 UTC, yangzhon commented on hw/cpu/Makefile.objs
> +common-obj-$(CONFIG_ARM_CORE) += core.o
Done, thanks!

2018-09-18 05:55 UTC, yangzhon commented on hw/vfio/stub.c
> + * QEMU i386 virt Platform stub
Done, thanks!

2018-09-18 06:01 UTC, yangzhon commented
@sameo ,

I addressed all your comments and please review again, thanks!

2018-09-18 10:06 UTC, sameo approved these changes
LGTM

2018-09-18 15:47 UTC, rbradford commented on default-configs/hw-common.mak
> +CONFIG_PCMCIA=y
There is only one file inside pcmcia/ that is not trivial and that is controlled by CONFIG_PXA2XX which is only turned on in arm-softmmu.mk.

So please move CONFIG_PCMCIA=y to that file instead

2018-09-18 15:47 UTC, rbradford commented on default-configs/hw-common.mak
> +CONFIG_BT=y
Have you considered piggy-backing on the back of CONFIG_BLUEZ instead?

2018-09-18 15:47 UTC, rbradford commented on default-configs/hw-common.mak
> +CONFIG_PS2_DEV=y
Have you looked at adding these only to those targets that actually use them?

2018-09-18 15:47 UTC, rbradford commented on default-configs/hw-common.mak
> +CONFIG_CHRP_NVRAM=y
This is not a virtual device - just some helper functions. It's only used by a couple of sun machines and a couple of nvram devices. I think you can be more specific than putting it in this file

2018-09-18 15:47 UTC, rbradford commented on default-configs/hw-common.mak
> +CONFIG_CHRP_NVRAM=y
Also the commit message is wrong.

2018-09-18 15:47 UTC, rbradford commented on default-configs/hw-common.mak
> +CONFIG_AUDIO=y
This is not a virtual device.

Compiling this out will break vl.c.

2018-09-18 15:47 UTC, rbradford commented on hw/block/Makefile.objs
> +common-obj-$(CONFIG_CDROM) += cdrom.o
This is only used by two devices. It would be better to do OR on CONFIG_IDE_CORE and CONFIG_SCSI.

This would also remove the need to do the stub stuff you do later.

2018-09-18 15:47 UTC, rbradford commented on hw/block/Makefile.objs
> +common-obj-$(CONFIG_HARD_DISK) += hd-geometry.o
I don't see the benefit of making this file conditional. You still needed to include it on the purely virt build...

2018-09-18 15:47 UTC, rbradford commented on default-configs/hw-common.mak
> +CONFIG_PCI_BRIDGE=y
Maybe only turn it on in makefiles that have CONFIG_PCI?

2018-09-18 15:47 UTC, rbradford commented on default-configs/hw-common.mak
> +CONFIG_WDT=y
I thought watchdog was in the configure script?

2018-09-18 15:47 UTC, rbradford commented on default-configs/hw-common.mak
> +CONFIG_VFIO_VGA=y
I think this should be in pci.mak instead.

2018-09-18 15:47 UTC, rbradford commented on default-configs/hw-common.mak
> +CONFIG_RAMFB=y
This is only used by ARM virt, PC and Q35 so this can be in more specific files.

2018-09-18 15:47 UTC, rbradford commented on default-configs/x86_64_virt-softmmu.mak
> +CONFIG_MEM_HOTPLUG=y
@mcastelino Let's worry about a virt-minimal default-config file later.

2018-09-18 15:47 UTC, rbradford commented on default-configs/x86_64_virt-softmmu.mak
> -include pci.mak
I'd rather see this commit add the new file in its minimal form. Rather than have the two previous commits that add it and then slightly reduce it.

2018-09-18 15:47 UTC, rbradford commented on default-configs/x86_64_virt-softmmu.mak
> -CONFIG_ACPI_NVDIMM=y
I don't think this should be deleted from this file at the moment. NVDIMM adds a lot of value to the virt platform.

2018-09-18 15:47 UTC, rbradford commented on default-configs/hw-common.mak
> +CONFIG_REGISTER=y
In your commit message you say this is only used on Xilinx. So why does it need to be included in every build?

2018-09-18 15:47 UTC, rbradford commented on default-configs/hw-common.mak
> +CONFIG_GPIO_IRQ=y
I think these files are only used on ARM.

2018-09-18 15:47 UTC, rbradford commented on default-configs/hw-common.mak
> +CONFIG_USB_CORE=y
As you can see from my comments. My gut feeling is by being a little bit more careful we can remove this file entirely.

2018-09-21 09:16 UTC, sameo commented
This is ready to be merged.
With this configure script:

```
$SRCDIR/configure \
 --disable-fdt \
 --disable-libiscsi \
 --disable-libnfs \
 --disable-libssh2 \
 --disable-linux-aio \
 --disable-lzo \
 --disable-modules \
 --disable-netmap \
 --disable-qom-cast-debug \
 --disable-seccomp \
 --disable-snappy \
 --disable-tcmalloc \
 --disable-tools \
 --disable-tpm \
 --disable-virtfs \
 --disable-tcg \
 --disable-slirp \
 --disable-capstone \
 --disable-xen \
 --disable-wdt \
 --disable-audio \
 --disable-bluetooth \
 --disable-usb-redir \
 --enable-attr \
 --enable-cap-ng \
 --enable-kvm \
 --enable-rbd \
 --enable-vhost-crypto \
 --enable-vhost-net \
 --enable-vhost-scsi \
 --enable-vhost-user \
 --enable-vhost-vsock \
 --enable-virtfs \
 --target-list=x86_64_virt-softmmu \
 --extra-cflags="$EXTRA_CFLAGS" \
 --extra-ldflags=" -pie -z noexecstack -z relro -z now" \
 --libdir=/usr/lib64/nemu \
 --libexecdir=/usr/libexec/nemu \
 --datadir=/usr/share/nemu
```

I can generate a list of unused files and automatically remove them to get down to the following code size:

```
-------------------------------------------------------------------------------
Language                 Files     Lines     Code  Comments   Blanks Complexity
-------------------------------------------------------------------------------
C                          539    321651   245840     33774    42037      37683
C Header                   524     91249    51389     29102    10758        977
```

down from 

```
-------------------------------------------------------------------------------
Language                 Files     Lines     Code  Comments   Blanks Complexity
-------------------------------------------------------------------------------
C                         1824   1313592  1035283    119525   158784     131849
C Header                  1429    245153   161133     55763    28257       3557
```

2018-09-21 11:21 UTC, rbradford commented on default-configs/alpha-softmmu.mak
> +include hw-common.mak
Since this file is empty. Maybe we could remove it from all the other files?

2018-09-21 11:21 UTC, rbradford commented on default-configs/x86_64_virt-softmmu.mak
> +
Can you revert the change that @yangzhon did to remove CONFIG_NVDIMM=y from here? I think we want to keep it in this file.

2018-09-21 11:21 UTC, rbradford commented on default-configs/tricore-softmmu.mak
> +include hw-common.mak
This looks strange? Has this changed because of the rebase?

2018-09-21 11:21 UTC, rbradford commented on configure
> +  ;;
How is this different to the bluez version? Is there a !bluez backend?

2018-09-21 11:43 UTC, sameo commented on default-configs/alpha-softmmu.mak
> +include hw-common.mak
Ah sorry, I meant to remove those but forgot.

2018-09-21 11:46 UTC, sameo commented on configure
> +  ;;
Yes, the BlueZ code is optional, you can have BT on without BlueZ support from the host.

However the BlueZ code is not relevant when BT is off. So you can have CONFIG_BT && CONFIG_BLUEZ, CONFIG_BT && !CONFIG_BLUEZ but not !CONFIG_BT && CONFIG_BLUEZ.

2018-09-21 11:46 UTC, sameo commented on default-configs/x86_64_virt-softmmu.mak
> +
Yes, makes sense.

2018-09-21 11:55 UTC, sameo commented on default-configs/alpha-softmmu.mak
> +include hw-common.mak
Done.

`git grep hw-common.mak` is empty now.

2018-09-21 11:55 UTC, sameo commented on default-configs/x86_64_virt-softmmu.mak
> +
Done as well.

2018-09-21 11:55 UTC, sameo commented on default-configs/tricore-softmmu.mak
> +include hw-common.mak
That's an odd one. It's untouched now.

2018-09-21 15:44 UTC, merged